database.address: localhost
database.name: minecraft
database.port: 3306
database.username: root
database.password: password
database.prefix: ""

chat.global.color: ""
chat.global.format: [{channel}] {prefix} {player}: {chatcolor}{suffix}{msg}

chat.moderator.color: ""
chat.moderator.format: [{channel}] {player}: {chatcolor}{msg}
